TRUNCATE TABLE "Recipes";

INSERT INTO "Recipes"
  ("Name", "Nationality", "ProteinGroup", "Ingredients", "Steps", "CookingTime")
VALUES
  ('Chicken Parmesan', 'Italian', 'Chicken', '2 large eggs@1 tablespoon minced garlic@2 tablespoons fresh chopped parsley@Salt and pepper to season@3 large chicken breasts halved horizontally to make 6 fillets@1 cup Panko breadcrumbs@1/2 cup breadcrumbs (Italian or golden)@1/2 cup fresh grated parmesan cheese@1 teaspoon garlic or onion powder@1/2 cup olive oil for frying@1 tablespoon olive oil@1 large onion chopped@2 teaspoons minced garlic@14 ounces (400 g) tomato puree (Passata)@Salt and pepper to taste@1 teaspoon dried Italian herbs@1 teaspoon sugar (optional)@',
    'Preheat oven 430F | 220C.@Lightly grease an oven tray (or baking dish) with non stick cooking oil spray; set aside@Whisk together eggs, garlic, parsley, salt and pepper in a shallow dish@Add chicken into the egg, rotating to evenly coat each fillet in the mixture@Cover with plastic wrap and allow to marinate for at least 15 minutes (or overnight night if time allows for a deeper flavour@When chicken is ready for cooking, mix bread crumbs, Parmesan cheese and garlic powder together in a separate shallow bowl@Dip chicken into the breadcrumb mixture to evenly coat@Heat oil in a large skillet over medium-high heat until hot and shimmering@Fry chicken until golden and crispy, (about 4-5 minutes each side@Place chicken on prepared baking tray / dish and top each breast with about 1/3 cup of sauce (sauce recipe below)@Top each chicken breast with 2-3 slices of mozzarella cheese and about 2 tablespoons parmesan cheese@Sprinkle with basil or parsley@Bake for 15-20 minutes, or until cheese is bubbling and melted, and the chicken is completely cooked throug@Heat oil in a medium-sized pot@Fry onion until transparent (about 3 minutes), then add the garlic until fragrant (about 30 seconds)@Add the tomato puree, salt and pepper to taste, Italian herbs and sugar (If using)@Cover with lid to simmer for about 8 minutes, or until sauce has thickened slightly@Taste test and adjust salt and pepper, if needed', '20 minutes');

INSERT INTO "Recipes"
  ("Name", "Nationality", "ProteinGroup", "Ingredients", "Steps", "CookingTime")
VALUES
  ('Chicken Osso Buco', 'Italian', 'Chicken', '1/4 cup all-purpose flour@4 Chicken Legs@2 tsp@ olive oil@1 large onion@2 medium carrots@1 small bulb fennel, chopped, or 2 medium stalks celery@3 clove garlic@3/4 c@ dry white wine@1 can low-sodium chicken broth@1 can diced tomatoes@1 1/2 tsp. chopped fresh rosemary or 1/2 tsp dried rosemary@Kosher salt and pepper@1 c. orzo@1/2 c. flat-leaf parsley@1 tbsp. grated lemon zest@',
    'Heat oven to 325F.@In a large resealable plastic bag, place the flour and the chicken pieces and shake to coat.@Heat the oil in a large ovenproof skillet over medium-high heat.@Add the chicken and cook, turning occasionally, until browned, about 8 minutes. Transfer the chicken to plate.@Reduce the heat to medium.@Add the onion, carrots, fennel and 2 tsp of the garlic to the saucepan and cook, covered, stirring occasionally, until golden brown and tender, 5 to 7 minutes.@Add the wine and cook, stirring and scraping up any brown bits for 1 minute.@Add the chicken broth, tomatoes, rosemary, 1/2 tsp salt and 1/4 tsp pepper and simmer for 4 minutes.@Return chicken to pan, cover and bake until the chicken is cooked through, 30 to 40 minutes.@Meanwhile, cook the orzo according to package directions. In a small bowl, combine the parsley, lemon zest and the remaining garlic.@Sprinkle chicken with parsley mixture and serve with cooked orzo.@', '30-40 minutes');
INSERT INTO "Recipes"
  ("Name", "Nationality", "ProteinGroup", "Ingredients", "Steps", "CookingTime")
VALUES
  ('Sun-Dried Tomato Chicken Florentine Pasta', 'Italian', 'Chicken', '8 ounces ziti or other pasta@1 tablespoon butter@1 lb. chicken, cut into bite sized pieces@1 tablespoon all purpose seasoning mix for the chicken@1/4 teaspoon cayenne@1 7-ounce jar DeLallo sun dried tomatoes, drained@3 cloves garlic@1 cup heavy cream@1/2 cups Mozzarella cheese@1/2 cup Parmesan cheese@2 cups spinach@1/2 cup chicken broth@Salt to taste@', 'Cook the pasta according to package directions. Drain and set aside.@Heat the butter in a skillet over medium high heat.@Add the chicken and sprinkle with the seasoning and the cayenne.@Saute until the chicken is cooked through.@Drain the oil from the sun dried tomatoes.@Chop into smaller pieces if you want.@Add them to the pan with the garlic and saute for a few minutes, until fragrant.@You will probably still get some of the oil from the sun dried tomatoes  thats okay.@Stir in the heavy cream and let the mixture come to a slow simmer.@Add the mozzarella cheese and parmesan cheese. Stir until the cheese is melted and incorporated.@Stir in the cooked pasta and spinach  the spinach will start to cook down almost immediately.@If needed, add in the chicken broth, a little at a time, to thin out the sauce. Season with salt to taste.@', '45 minutes');


INSERT INTO "Recipes"
  ("Name", "Nationality", "ProteinGroup", "Ingredients", "Steps", "CookingTime")
VALUES
  ('Pineapple Chicken', 'Asian', 'Chicken', '1 tbsp. vegetable oil@1 lb. boneless skinless chicken thighs, cut into 1" pieces@Kosher salt@Freshly ground black pepper@1 red bell pepper, chopped@3/4 c. canned pineapple juice@1/4 c. low-sodium soy sauce@1/4 c. brown sugar@2 tbsp. hoisin sauce@2 cloves garlic, minced@1/2 jalapeno, minced (seeded if desired)@2 tsp. cornstarch@1 c. pineapple chunks@1/4 c. cashews@Sliced green onions, for serving@Cooked white rice, for serving@Lime wedges, for serving@', 'In a large skillet over medium-high heat, heat oil.@Season chicken with salt and pepper and cook, turning occasionally, until golden, 5 minutes.@Stir in bell pepper and cook until just tender, 3 minutes more.@Meanwhile, in a small saucepan, combine pineapple juice, soy sauce, brown sugar, hoisin sauce, garlic, and jalapeno and bring to a simmer.@Make a slurry: In a small bowl whisk together 2 tsp. water and cornstarch until combined, then whisk into saucepan.@Cook until thickened, about 5 minutes.@Pour sauce over chicken and let simmer 3 minutes. Stir in pineapple and cashews.@Garnish with green onions and serve with rice and lime.@', '20 minutes');
INSERT INTO "Recipes"
  ("Name", "Nationality", "ProteinGroup", "Ingredients", "Steps", "CookingTime")
VALUES
  ('Chicken Chow Mein', 'Asian', 'Chicken', '12 oz. refrigerated chow mein noodles or dry spaghetti@
1 tbsp. sesame oil@
1 lb. boneless skinless chicken thighs, cut into 1" pieces@Kosher salt@Freshly ground black pepper@1 clove garlic, minced@1 tsp. freshly grated ginger@1 carrot, grated@1/2 head small cabbage, shredded@1/4 c. low-sodium chicken broth@1/4 c. low-sodium soy sauce@2 tbsp. oyster sauce@Thinly sliced green onions, for garnish@Toasted sesame seeds, for garnish@', 'In a large pot of salted boiling water, cook noodles just shy of al dente according to package instructions, then drain immediately.@In a large skillet over medium-high heat, heat oil.@Season chicken with salt and pepper.@Add chicken and cook until golden and crispy, 7 to 8 minutes.@Move chicken to one side of skillet, and to other side, add garlic, ginger, carrot, and cabbage and cook until tender, 3 minutes.@Meanwhile, make sauce: In a medium bowl, whisk together broth, soy sauce, and oyster sauce.@Pour sauce over skillet and add cooked noodles, tossing to combine.@Garnish with green onions and sesame seeds before serving.@', '30 minutes');